shaka-project/generic-webdriver-server

.github/workflows/test.yaml
backends/chromecast/package.json
backends/chromeos/package.json
backends/fake/package.json
backends/tizen/package.json
backends/xboxone/package.json
package.json

Although there aren't any real tests (see #31), we can run the linter
on new PRs.  When we add tests later, the workflow will activate them
through npm test.

ci: Add test workflow

---

.github/workflows/test.yaml
backends/chromecast/package.json
backends/chromeos/package.json
backends/fake/package.json
backends/tizen/package.json
backends/xboxone/package.json

Configure git in the test workflow to check out code with LF line
endings on Windows, so that we pass linter checks.
Fixes #33

ci: Fix linter errors on Windows

---

.github/workflows/release-please.yaml

The workflow seemed to be interrupted on backends/fake/ otherwise, presumably due to a failure on `npm view`

ci: Skip private packages before checking release versions

---

base/generic-webdriver-server.js

When shutting down the server, don't just initiate session closure.  Actually wait for the session to close.
Issue #44

fix: Await session closure on shutdown

---

backends/xboxone/package-lock.json
backends/xboxone/package.json
backends/xboxone/xbox-one-utils.js
backends/xboxone/xbox-one-webdriver-server.js

This fixes several issues with reliability, especially when running
tests in a loop back-to-back without a delay between.  In those cases,
the Xbox One would frequently fail to launch or to uninstall the app.
Specific changes:
- Await session closure on shutdown (fixed in base package v1.1.4)
- Log but swallow app uninstall errors (don't report to the client)
- Retry when app launch fails (after a delay to let Xbox recover)
Closes #44

fix(xbox): Fix several reliability issues

---

backends/xboxone/README.md

Sign-in is required for WebView on Xbox One.  If you don't enable
instant sign-in, a manual sign-in is required after every reboot or OS
update.  This documents the need and process for instant sign-in.

docs: Add documentation on instant sign-in for Xbox One

---

backends/tizen/tizen-utils.js

Because the container's user ID may not match the host user ID, we need the temp folder to be world-readable.

fix(tizen): Fix Docker host permissions

---

backends/chromecast/cast-utils.js
backends/chromecast/chromecast-webdriver-cli.js
backends/chromecast/chromecast-webdriver-server.js

This adds the --show-serial flag to the Chromecast CLI tool, to instruct Chromecast devices to show their serial numbers and read them aloud.

feat: Instruct Chromecasts to show their serial numbers

---

backends/tizen/tizen-studio-docker/base/Dockerfile
backends/tizen/tizen-utils.js

Upgrading Tizen Studio to 5.0 (released just a couple weeks ago) seems to fix the certificate issues we've been having.
Closes #57

fix: Fix Tizen cert issues in Docker image

---

backends/chromecast/chromecast-webdriver-cli.js

Older versions of yargs only allow you to call conflicts() with two arguments, not three.  For greater compatibility, use the two-argument version of the call.

fix: Fix yargs compatibility

---

.allstar/binary_artifacts.yaml
base/java/third_party/SOURCES.txt

We include three binary jars in this repository.  This asks allstar (Google scanning tool) to allow this.
Closes #67

fix: Override allstar settings for binaries

---

backends/chromecast/cast-utils.js

After we launch the requested receiver app, we should shut down the connection explicitly.  Otherwise, the socket has to time out before the calling application in nodejs can terminate.  This is because nodejs keeps the main thread running so long as anything async could occur, including events on handles and sockets.

fix(chromecast): Speed up shutdown

---

.github/workflows/test.yaml
backends/chromecast/receiver.html

Expose `cast.__platform__` asynchronously through postMessage. Cannot be used to proxy synchronous calls, but could be used for debugging or with an async shim and `await` on all calls from the client.

feat(chromecast): Allow async access to `cast.__platform__` via postMessage

---

backends/chromecast/package-lock.json
backends/chromecast/package.json
backends/chromeos/package-lock.json
backends/chromeos/package.json
backends/fake/package-lock.json
backends/fake/package.json
backends/tizen/package-lock.json
backends/tizen/package.json
backends/xboxone/package-lock.json
backends/xboxone/package.json
base/package-lock.json
base/package.json

This updates all dependencies in all packages.
`yargs` used to be transitively included through the base package, but that no longer works, so it is now explicitly given as a dependency in each backend.

chore: Update deps

---

backends/chromeos/package-lock.json
backends/chromeos/package.json

node-fetch is an ES module, and you can't require() ESM from a non-ESM script. I'm not sure when this changed, or with what versions of node and this package it used to work, but downgrading to node-fetch v2 gives us the non-ESM version that works.

fix(chromeos): Fix loading of node-fetch library

---

backends/chromeos/chromeos-utils.js

In our deployment under a service account in `shaka-lab-node`, ~/.ssh may not exist yet.

fix(chromeos): Create private key folder if missing

---

backends/chromeos/scripts/launch_page.sh

It seems as if the short sleep time when monitoring the launch of session manager is no longer working correctly, with errors thrown inconsistently during test runs.  Using a longer sleep time and fewer loops seems to fix it.

fix(chromeos): Fix session manager timing

---

backends/chromeos/chromeos-utils.js

Since upgrading node-ssh, we sometimes get an exit code of 0, other times an exit code of null.  This makes the tool more flexible in interpreting those codes.

fix(chromeos): Fix node-ssh exit code interpretation

---

backends/chromecast/receiver-v1.html

To prepare for a v2 client and receiver app, this copies receiver.html (with some additional comments) to receiver-v1.html.  After merging this change, the registration for the v1 receiver app ID will be changed to point to receiver-v1.html.  This will free us to make breaking changes in receiver.html under a new app ID.
It is important for a smooth transition to make a copy of receiver.html first and not simply rename it, because there will be a transition period where some Chromecasts under test will still refer to the old URL.  This should be < 48 hours after merge.

feat(chromecast)!: Fork receiver app v1

---

backends/chromecast/README.md
backends/chromecast/cast-utils.js
backends/chromecast/how-it-works.md
backends/chromecast/receiver-deployment.md
backends/chromecast/receiver.html

This introduces an optional redirect mode, which changes the top URL instead of using an iframe to host content.  This requires the Cast SDK to be loaded at the destination URL.  This can be used for Shaka Player testing, but not for every URL you might want to see on a Chromecast.
This requires deployment to a new receiver app ID.

feat(chromecast)!: Add v2 receiver app with a redirect mode

---

backends/tizen/README.md
backends/tizen/how-it-works.md
backends/tizen/tizen-studio-docker/README.md
backends/tizen/tizen-studio-docker/tv-3.0/Dockerfile
backends/tizen/tizen-utils.js

Google Container Registry is imposing more painful restrictions on us, so we are migrating the Tizen Studio TV docker image from GCR to GHCR (GitHub Container Registry).  This should be simpler overall for an open source project hosted on GitHub, and should also work well for forks.
Because the older registry is being shut down, this is a breaking change, and the Tizen v1.x packages will be marked as deprecated.

feat(tizen)!: Migrate Google Container Registry to GitHub Container Registry

---

.github/workflows/release-please.yaml
.github/workflows/test.yaml

This was found by auditing workflows based on research published here:
https://github.com/joeyparrish/workflow-cheat-sheet
The research was prompted by a workflow bug in Shaka Streamer

ci: Fix workflow events

---

.github/workflows/release-please.yaml
.github/workflows/test.yaml

Also:
- Upgrades release-please
- Upgrades nodejs version (old one was EOL)

ci: Update release workflow tokens and permissions
